SConsignFile('.scons/sconsign')

env = Environment()

conf = env.Configure(conf_dir='.scons', log_file='.scons/log')
env = conf.Finish()

env.ParseConfig('pkg-config --cflags --libs glib-2.0 gtk+-2.0 libglade-2.0 gconf-2.0')

env.Append(CCFLAGS=['-g', '-W', '-Wall', '-pedantic', '-std=c99'])
env.Append(CPPDEFINES=['-DDATADIR=\\"/home/sciyoshi/Build/torque/data\\"', '-DTORQUE_VERSION_MAJOR=0', '-DTORQUE_VERSION_MINOR=1'])
env.Append(CPPPATH=['#/src/libtorque'])
env.Append(LIBPATH=['#/src/libtorque'])

env.Export('env')

env.SConscript(['src/SConscript', 'data/SConscript'])
