Import('*')

env.Command('bittorque-glade.h', ['#/data/bittorque.glade'], 'python tools/variablize.py $SOURCE $TARGET bittorque_glade')
env.Command('bittorque-icon.h', ['#/data/bittorque.png'], 'gdk-pixbuf-csource --stream --name=bittorque_icon $SOURCE > $TARGET')

if envgtk['static_gnet']:
	envgtk.Append(_LIBFLAGS=' -Xlinker /usr/local/lib/libgnet-2.0.a')

envgtk.Program('bittorque',
	['bittorque.c',
	 'bittorque-open-dialog.c'])
