Import('*')

env.StaticLibrary('torque',
	['torque-utils.c',
	 'torque-manager.c',
	 'torque-torrent.c',
	 'torque-torrent-file.c',
	 'torque-torrent-peer.c',
	 'torque-torrent-tracker.c',
	 'torque-bencode.c',
	 'rc4.c',
	 'sha1.c'])
